VM_MEMORY = 1024
VM_CPU    = 1

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # ===== SERVER VM =====
  config.vm.define "yachenS" do |server|
    server.vm.hostname = "yachenS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "yachen"
      vb.memory = VM_MEMORY
      vb.cpus   = VM_CPU
    end

    server.vm.provision "all_in_one", type: "shell", path: "./all_in_one.sh"
 end
end

