VM_MEMORY = 1024
VM_CPU    = 1

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"

  # ===== SERVER VM =====
  config.vm.define "yachenS" do |server|
    server.vm.hostname = "yachenS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "abait-ta"
      vb.memory = VM_MEMORY
      vb.cpus   = VM_CPU
    end

    server.vm.provision "install_k3s_server", type: "shell", inline: <<-SHELL
      bash /vagrant/scripts/install_server.sh
    SHELL
  end

  # ===== AGENT VM =====
  config.vm.define "yachenSW" do |agent|
    agent.vm.hostname = "yachenSW"
    agent.vm.network "private_network", ip: "192.168.56.111"

    agent.vm.provider "virtualbox" do |vb|
      vb.name = "yachen"
      vb.memory = VM_MEMORY
      vb.cpus   = VM_CPU
    end

    agent.vm.provision "install_k3s_agent", type: "shell", inline: <<-SHELL
      bash /vagrant/scripts/install_worker.sh
    SHELL
  end
end

